version: '3.9'
services:
  db:
    ports:
      - "5432:5432"
    env_file:
      - ./env/db_service.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data
  identity:
    env_file:
      - ./env/identity_service.env
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
      - /d/temp/keys:/root/.aspnet/DataProtection-Keys
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet RealRender.IdentityService.dll"
  product:
    env_file:
      - ./env/product_api_service.env
    ports:
      - "7000:7000"
      - "7001:7001"
    depends_on:
      - identity
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro
      - /d/temp/keys:/root/.aspnet/DataProtection-Keys
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet RealRender.ProductApiService.dll"
volumes:
  db_data:
    name: realrender_db
