version: '3.9'
services:
  db:
    container_name: realrender_db_service
    image: postgres:15.0-alpine
  identity:
    container_name: realrender_identity_service
    image: ${DOCKER_REGISTRY-}realrenderidentityservice
    build:
      context: .
      dockerfile: RealRender.IdentityService/Dockerfile
  product:
    container_name: realrender_product_api_service
    image: ${DOCKER_REGISTRY-}realrenderproductapiservice
    build:
      context: .
      dockerfile: RealRender.ProductApiService/Dockerfile
